# USER SPECIFIED:
# path to directory containing fastq files
data_path: '/project/lbarreiro/DATA/SLAM-seq/pilot_2025.08.19/FastX'
# path to genome assembly for STAR alignment
assembly_path: '/project/lbarreiro/SHARED/REFERENCES/Homo_sapiens/GATK/GRCh38/GRCh38.primary_assembly.genome.fa'
# path to container for GEDI
container_path: '/project/lbarreiro/USERS/austin/containers/gedi_R.sif'

# Provide the lanes used in the sequencing run
sequencing_lanes: [5, 6, 7, 8]

# R1 adapter sequence, reverse complement (as it appears in the reads)
adapter_sequence_r1_rc: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA'
# R2 adapter sequence, reverse complement (as it appears in the reads)
adapter_sequence_r2_rc: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'

# identifiers for each donor (one complete set of timepoints + 1 no4sU control)
donors:
  - donor1_rep1
  - donor2_rep1
  - donor1_rep2

# In here, map each sample ID to a donor ID and a timepoint (make numeric, pipeline will attach units)
sample_ids:
  LB-HT-28s-HT-01_S1:
    donor: donor1_rep1
    timepoint: 0
  LB-HT-28s-HT-02_S2:
    donor: donor1_rep1
    timepoint: 15
  LB-HT-28s-HT-03_S3:
    donor: donor1_rep1
    timepoint: 30
  LB-HT-28s-HT-05_S5:
    donor: donor1_rep1
    timepoint: 60
  LB-HT-28s-HT-06_S6:
    donor: donor1_rep1
    timepoint: 90
  LB-HT-28s-HT-07_S7:
    donor: donor1_rep1
    timepoint: 105
  LB-HT-28s-HT-08_S8:
    donor: donor1_rep1
    timepoint: 120
  LB-HT-28s-HT-09_S9:
    donor: donor1_rep1  # Primary assignment
    timepoint: 'no4sU'
  LB-HT-28s-HT-10_S10:
    donor: donor2_rep1
    timepoint: 0
  LB-HT-28s-HT-12_S12:
    donor: donor2_rep1
    timepoint: 30
  LB-HT-28s-HT-16_S16:
    donor: donor2_rep1
    timepoint: 105
  LB-HT-28s-HT-17_S17:
    donor: donor2_rep1
    timepoint: 120
  LB-HT-28s-HT-18_S18:
    donor: donor2_rep1
    timepoint: 'no4sU'
  LB-HT-28s-JL-01_S19:
    donor: donor1_rep2
    timepoint: 0
  LB-HT-28s-JL-02_S20:
    donor: donor1_rep2
    timepoint: 15
  LB-HT-28s-JL-03_S21:
    donor: donor1_rep2
    timepoint: 30
  LB-HT-28s-JL-04_S22:
    donor: donor1_rep2
    timepoint: 45
  LB-HT-28s-JL-05_S23:
    donor: donor1_rep2
    timepoint: 60
  LB-HT-28s-JL-06_S24:
    donor: donor1_rep2
    timepoint: 75
  LB-HT-28s-JL-07_S25:
    donor: donor1_rep2
    timepoint: 90
  LB-HT-28s-JL-08_S26:
    donor: donor1_rep2
    timepoint: 105
  LB-HT-28s-JL-09_S27:
    donor: donor1_rep2
    timepoint: 120

# Map donors to their control samples
donor_controls:
  donor1_rep1: "LB-HT-28s-HT-09_S9"
  donor2_rep1: "LB-HT-28s-HT-18_S18"
  donor1_rep2: "LB-HT-28s-HT-09_S9"

# string to specify no4sU control. A "timepoint" in the sense that it gets added at the end of the filename where the timepoint would go, but doesn't represent a true point in time.
control_timepoint: 'no4sU'

# don't change this, it appears to be hard-coded in GEDI itself. Silly, I know.
gedi_index_dir: 'config/genomic'