name: /project/lbarreiro/USERS/austin/envs/slamseq_v2
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - alsa-lib=1.2.14=hb9d3cd8_0
  - amply=0.1.6=pyhd8ed1ab_1
  - anndata=0.12.2=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - array-api-compat=1.12.0=py312he3bba80_0
  - attrs=25.4.0=pyh71513ae_0
  - bedtools=2.31.1=h13024bc_3
  - blas=2.136=openblas
  - blas-devel=3.9.0=36_h1ea3ea9_openblas
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=hf7d4471_0
  - brotli-python=1.1.0=py312h1289d80_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.17.1=h4257ac4_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=2.0.1=py312h06a4308_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312h35888ee_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - coin-or-cbc=2.10.12=h4d16d09_4
  - coin-or-cgl=0.60.9=hc46dffc_6
  - coin-or-clp=1.17.10=hc03379b_3
  - coin-or-osi=0.108.11=hf4fecb4_7
  - coin-or-utils=2.11.12=hc93afbd_6
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - colormath=3.0.0=pyhd8ed1ab_4
  - conda-inject=1.3.2=pyhd8ed1ab_0
  - configargparse=1.7.1=pyhe01879c_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.3.1=py312hdb19cb5_0
  - cpython=3.12.12=py312hd8ed1ab_0
  - crc32c=2.7.1=py312h5eee18b_0
  - cryptography=46.0.2=py312hee9fe19_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - docutils=0.22.2=pyhd8ed1ab_0
  - donfig=0.8.1.post1=py312h06a4308_0
  - dpath=2.2.0=pyha770c72_0
  - eido=0.2.4=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fastp=1.0.1=heae3180_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py312hee96239_0
  - freetype=2.14.1=ha770c72_0
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.13.0=nompi_py312hedeef09_100
  - harfbuzz=12.1.0=h15599e2_0
  - hdf5=1.14.3=nompi_h2d575fe_109
  - hisat-3n=0.0.3=h503566f_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.22.1=h566b1c6_0
  - humanfriendly=10.0=pyh707e725_8
  - humanize=4.12.2=py312h06a4308_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - immutables=0.21=py312h4c3975b_2
  - importlib-metadata=8.5.0=py312h06a4308_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - isa-l=2.31.1=hb9d3cd8_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=py312h06a4308_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - kaleido-core=0.2.1=h7c8854e_0
  - kallisto=0.50.1=h6de1650_2
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.8=py312h6a678d5_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - legacy-api-wrap=1.4.1=pyhd8ed1ab_0
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=36_h4a7cf45_openblas
  - libcblas=3.9.0=36_h0358290_openblas
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.86.0=h1fed272_0
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=36_h47877c9_openblas
  - liblapacke=3.9.0=36_h6ae95b6_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.50=h421ea60_1
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.7.1=h8261f1e_0
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.45.1=py312h7424e68_0
  - logmuse=0.2.8=pyhd8ed1ab_1
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.8=py312h06a4308_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h8a5da7c_0
  - mathjax=2.7.5=h06a4308_0
  - matplotlib-base=3.10.6=py312h71dd3da_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - msgpack-python=1.1.1=py312h6a678d5_0
  - multiqc=1.31=pyhdfd78af_0
  - narwhals=2.7.0=py312h06a4308_0
  - natsort=8.4.0=py312h06a4308_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.5=py312h06a4308_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numba=0.62.1=py312h907b442_0
  - numcodecs=0.14.1=py312h2c38b39_0
  - numexpr=2.11.0=py312hccd6f0b_1
  - numpy=1.26.4=py312heda63a1_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - openblas=0.3.30=pthreads_h6ec200e_2
  - openjdk=24.0.2=h5755bd7_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - patsy=1.0.1=py312h06a4308_0
  - pcre2=10.46=h1321c63_0
  - pephubclient=0.4.4=pyhd8ed1ab_1
  - peppy=0.40.7=pyhd8ed1ab_2
  - perl=5.32.1=7_hd590300_perl5
  - pillow=11.3.0=py312h7b42cdd_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - plac=1.4.5=pyhd8ed1ab_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.3.0=py312he3bba80_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - polars=1.34.0=pyh6a1acc5_0
  - polars-lts-cpu=1.34.0.deprecated=hc364b38_0
  - polars-runtime-32=1.34.0=py310hffdcd12_0
  - polars-runtime-compat=1.34.0=py310hbcd5346_0
  - psutil=7.1.0=py312h4c3975b_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulp=2.8.0=py312hd0750ca_3
  - py-cpuinfo=9.0.0=py312h06a4308_0
  - pyaml-env=1.2.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.0=pyh3cfb1c2_0
  - pydantic-core=2.41.1=py312h868fb18_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pynndescent=0.5.13=py312h06a4308_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytables=3.10.2=py312h2895ec7_2
  - pytest=8.4.2=pyhd8ed1ab_0
  - python=3.12.11=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.0=py312h06a4308_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_0
  - python-kaleido=0.2.1=py312h06a4308_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - regex=2025.9.1=py312hee96239_0
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-oauthlib=1.4.0=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_1
  - rich=14.2.0=pyhcf101f3_0
  - rich-click=1.9.3=pyhd8ed1ab_0
  - rpds-py=0.27.1=py312h868fb18_1
  - samtools=1.22.1=h96c455f_0
  - scanpy=1.7.2=pyhdfd78af_0
  - scikit-learn=1.7.2=py312h505adc9_0
  - scipy=1.16.2=py312ha592af2_0
  - seaborn=0.13.2=py312h06a4308_3
  - setuptools=80.9.0=pyhff2d567_0
  - setuptools-scm=8.3.1=py312h06a4308_1
  - setuptools_scm=8.3.1=hd3eb1b0_1
  - shellingham=1.5.4=pyhd8ed1ab_1
  - sinfo=0.3.1=py_0
  - six=1.17.0=pyhe01879c_1
  - slack-sdk=3.37.0=pyhd8ed1ab_0
  - slack_sdk=3.37.0=hd8ed1ab_0
  - smart_open=7.3.1=pyhcf101f3_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake=9.13.1=hdfd78af_0
  - snakemake-executor-plugin-slurm=1.8.0=pyhdfd78af_0
  - snakemake-executor-plugin-slurm-jobstep=0.3.0=pyhdfd78af_0
  - snakemake-interface-common=1.22.0=pyhd4c3c12_0
  - snakemake-interface-executor-plugins=9.3.9=pyhdfd78af_0
  - snakemake-interface-logger-plugins=1.2.4=pyhdfd78af_0
  - snakemake-interface-report-plugins=1.2.0=pyhdfd78af_0
  - snakemake-interface-scheduler-plugins=2.0.1=pyhd4c3c12_0
  - snakemake-interface-storage-plugins=4.2.3=pyhd4c3c12_0
  - snakemake-minimal=9.13.1=pyhdfd78af_0
  - snakemake-storage-plugin-http=0.3.0=pyhdfd78af_0
  - spectra=0.0.11=pyhd8ed1ab_2
  - sqlite=3.50.2=hb25bd0a_1
  - statsmodels=0.14.5=py312h76ea63d_0
  - stdlib-list=0.10.0=py312h06a4308_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2022.0.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tiktoken=0.9.0=py312h52b74c6_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.3.0=pyhcf101f3_0
  - tqdm=4.67.1=py312he106c6f_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typeguard=4.2.1=py312h06a4308_0
  - typer=0.19.2=pyhef33e25_0
  - typer-slim=0.19.2=pyhcf101f3_0
  - typer-slim-standard=0.19.2=h6e3bb38_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - umap-learn=0.5.9.post2=py312h7900ff3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py312h4c3975b_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - yte=1.8.1=pyha770c72_0
  - zarr=3.1.3=pyhcf101f3_0
  - zipp=3.21.0=py312h06a4308_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.0.7=h5eee18b_0
  - zstandard=0.25.0=py312h5253ce2_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: /project/lbarreiro/USERS/austin/envs/slamseq_v2
