# cluster settings:
executor: slurm
cores: 32
jobs: 8
use-singularity: true # activate singularity for container
singularity-args: "--bind /project/lbarreiro,/scratch/midway3/aszatrowski" # give container access to all of lbarreiro & personal scratch
default-resources:
  slurm_account: pi-lbarreiro # bill Luis
  slurm_partition: lbarreiro # don't bill Luis
